### ISSUE TITLE
Great Job ! How do I convert existing Express App with several routes to a bunch of Serverless Functions

### ISSUE THREAD

**Issue by qnxdev** [jlarmstrongiv/create-vercel-http-server-handler#5]
I did not understand how a single function /api/vercel will handle all requests instead of several functions handling corresponding requests.

Can you please explain

**Comment by jlarmstrongiv** [comment]
Sure, I think the best explanation is the API Routes documentation https://nextjs.org/docs/api-routes/dynamic-api-routes

To handle all routes, you can use `[...slug].js`

**Comment by qnxdev** [comment]
But  <[...slug.js]> still be a single overloaded function right?

**Comment by jlarmstrongiv** [comment]
@qnxdev Ahh yes, I misunderstood your question.  

Most of the time, I keep a single overloaded function.  However, it is possible to use multiple handlers across multiple sub-routes.

For more complex apps, I find NestJS supports splitting apps into multiple microservices well via [monorepos](https://docs.nestjs.com/cli/monorepo) (apps and libs), [lazy loading](https://docs.nestjs.com/fundamentals/lazy-loading-modules), and [webpack bundling](https://docs.nestjs.com/faq/serverless).  That generally means each app becomes a function and listens to sub-routes, while importing the code it needs from the libs.  I usually apply the middleware (cors, guards, interceptors) to all the apps.  Often, it becomes difficult to manage dependencies under the 50mb limit, so I end up using https://www.serverless.com/blog/container-support-for-lambda

Unfortunately, there’s no easy way to break an existing express app into multiple functions if the code is very intertwined—be prepared to refactor.

**Comment by qnxdev** [comment]
I splited it as (req,res)=>{} functions and used those functions in the express app route callbacks, when I run locally. In production, these will work as individual functions with Vercel's node runtime

**Comment by qnxdev** [comment]
I think there's great scope if anyone can solve it with a package

**Comment by jlarmstrongiv** [comment]
Recommended reading https://github.com/nestjs/nest/issues/1706#issuecomment-579248915

You’re welcome to explore these repos:
- https://github.com/vercel/ncc
- https://github.com/vercel/nft
- https://webpack.js.org/configuration/output/#outputlibrarytype

But, having tried that path myself, I don’t think it’s worth it for a small team.  I found there are many breaking issues when you try to do anything serious that involves lazy loading and/or native modules (think database connectors, image libraries, machine learning, fast libraries).  The NestJS repo has many issues from bundler setups that don’t cover all use cases.  And with the docker with lambda update, concerns about the size of those extra dependencies don’t really matter anymore.

At this point, I use a mix of bundling and excluding native packages via webpack externals (as described in https://docs.nestjs.com/faq/serverless) for my apps.  

With the new ESM only modules coming to a package near you https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c and my prior explorations, I think that building a bundling system is far outside the scope of what I want to deal with in a normal project.

**Comment by qnxdev** [comment]
Since Vercel support golang, that's one of my considerations. Do you think go will allow a low latency operation and give a performance advantage on scale?

**Comment by jlarmstrongiv** [comment]
I’ve heard good things about golang.  Personally, I really like it’s typesafety, compilation to a small binary, and the quality of its standard library.  I’ve considered it before.

But, it really just depends on the project.  If I have one that requires machine learning (AI), then I’m definitely using a Python framework—Django or Flask.  Solid frameworks like Ruby on Rails or Django makes it easy to build complete systems and values convention over configuration.  JavaScript/TypeScript is nice to reduce cognitive load from switching between multiple languages.  Golang sounds cool, but often the best tool for makers/entrepreneurs is the one you already know (and I haven’t had the opportunity or found the best course to learn golang).  The company you work with will probably make the decision for you.  

I’m pretty happy with NestJS and Serverless, even though it took a couple days to put all the pieces together:
- https://docs.nestjs.com/faq/serverless
- https://docs.nestjs.com/cli/monorepo#monorepo-mode
- https://www.npmjs.com/package/@vendia/serverless-express
- https://www.serverless.com/blog/container-support-for-lambda

Sure, my containers could be smaller or I could reduce startup time further, but my project still scaled to 350,000 requests for only $300.  If I tried to run the same process on a single machine rather than lambdas, it would have taken 60 days vs 2 days to complete all the tasks (image processing).  

So pick the language and framework that best fits your goals (like python for AI) or is the one you already know
